### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by caicaishmily** [cf-natali/ntplib#17]
Can anybody help me ?

```shell
>>> import ntplib
>>> from time import ctime
>>> c = ntplib.NTPClient()
>>> response = c.request('ntp.aliyun.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/kspython3.7/lib/python3.7/site-packages/ntplib.py", line 313, in request
    s.sendto(query_packet.to_data(), sockaddr)
PermissionError: [Errno 1] Operation not permitted
>>> response = c.request('ntp.aliyun.com', version=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/kspython3.7/lib/python3.7/site-packages/ntplib.py", line 313, in request
    s.sendto(query_packet.to_data(), sockaddr)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by cf-natali** [comment]
Hi @caicaishmily ,

This isn't an issue with `ntplib`, but with your operating system.
Looks like `sendto` is returning `EPERM`, which shouldn't happen.
Might be due to a firewall or some kind of security module etc - I suggest you try to search for `sendto` and `EPERM` together with whatever operating system you're using, to get you started.

Good luck!
